# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_USER: emil
      DATABASE_PASSWORD: emilgan12
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_NAME: fastupdb
    volumes:
      - ./Backend:/usr/src/app
      - ./DLS:/usr/src/DLS
    restart: always

  db:
    image: postgres:15
    container_name: fastapi_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: emil
      POSTGRES_PASSWORD: emilgan12
      POSTGRES_DB: fastupdb
    volumes:
      - pgdata:/var/lib/postgresql/data

#  frontend:
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    depends_on:
#      - backend
#    ports:
#      - "3000:3000"

volumes:
  pgdata: