version: "3.9"

services:
  db:
    image: postgres:15
    container_name: easytravelbd
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: emil
      POSTGRES_PASSWORD: emilgan12
      POSTGRES_DB: fastupdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
